/*
 * ==========================================
 * |          GENERATED BY SUPAZOD          |
 * ==========================================
 */

import { z } from "zod";
import { type Json } from "./types";

export const jsonSchema: z.ZodSchema<Json> = z.lazy(() =>
  z
    .union([
      z.string(),
      z.number(),
      z.boolean(),
      z.record(z.string(), z.union([jsonSchema, z.undefined()])),
      z.array(jsonSchema),
    ])
    .nullable(),
);

export const publicAlatRowSchema = z.object({
  company: z.string(),
  harga: z.number().nullable(),
  harga_bulanan: z.number(),
  harga_harian: z.number(),
  id: z.number(),
  initial_stok: z.number().nullable(),
  name: z.string(),
});

export const publicAlatInsertSchema = z.object({
  company: z.string(),
  harga: z.number().optional().nullable(),
  harga_bulanan: z.number(),
  harga_harian: z.number(),
  id: z.number().optional(),
  initial_stok: z.number().optional().nullable(),
  name: z.string(),
});

export const publicAlatUpdateSchema = z.object({
  company: z.string().optional(),
  harga: z.number().optional().nullable(),
  harga_bulanan: z.number().optional(),
  harga_harian: z.number().optional(),
  id: z.number().optional(),
  initial_stok: z.number().optional().nullable(),
  name: z.string().optional(),
});

export const publicAlatRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("alat_company_fkey"),
    columns: z.tuple([z.literal("company")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("company"),
    referencedColumns: z.tuple([z.literal("name")]),
  }),
]);

export const publicCompanyRowSchema = z.object({
  name: z.string(),
});

export const publicCompanyInsertSchema = z.object({
  name: z.string(),
});

export const publicCompanyUpdateSchema = z.object({
  name: z.string().optional(),
});

export const publicRecordRowSchema = z.object({
  alat_name: z.string(),
  company_name: z.string(),
  id: z.number(),
  keluar: z.number().nullable(),
  masuk: z.number().nullable(),
  tanggal: z.string(),
});

export const publicRecordInsertSchema = z.object({
  alat_name: z.string(),
  company_name: z.string(),
  id: z.number().optional(),
  keluar: z.number().optional().nullable(),
  masuk: z.number().optional().nullable(),
  tanggal: z.string(),
});

export const publicRecordUpdateSchema = z.object({
  alat_name: z.string().optional(),
  company_name: z.string().optional(),
  id: z.number().optional(),
  keluar: z.number().optional().nullable(),
  masuk: z.number().optional().nullable(),
  tanggal: z.string().optional(),
});

export const publicRecordRelationshipsSchema = z.tuple([
  z.object({
    foreignKeyName: z.literal("record_company_name_fkey"),
    columns: z.tuple([z.literal("company_name")]),
    isOneToOne: z.literal(false),
    referencedRelation: z.literal("company"),
    referencedColumns: z.tuple([z.literal("name")]),
  }),
]);

export const publicRecordPushLogRowSchema = z.object({
  id: z.number(),
  batch_id: z.string(),
  user_id: z.string().nullable(),
  action_type: z.enum(["push", "delete", "restore"]),
  record_ids: z.array(z.number()),
  records_data: jsonSchema,
  records_count: z.number(),
  description: z.string().nullable(),
  created_at: z.string(),
  rolled_back_at: z.string().nullable(),
  rolled_back_by_batch_id: z.string().nullable(),
});

export const publicRecordPushLogInsertSchema = z.object({
  id: z.number().optional(),
  batch_id: z.string().optional(),
  user_id: z.string().optional().nullable(),
  action_type: z.enum(["push", "delete", "restore"]),
  record_ids: z.array(z.number()),
  records_data: jsonSchema,
  records_count: z.number(),
  description: z.string().optional().nullable(),
  created_at: z.string().optional(),
  rolled_back_at: z.string().optional().nullable(),
  rolled_back_by_batch_id: z.string().optional().nullable(),
});

export const publicRecordPushLogUpdateSchema = z.object({
  id: z.number().optional(),
  batch_id: z.string().optional(),
  user_id: z.string().optional().nullable(),
  action_type: z.enum(["push", "delete", "restore"]).optional(),
  record_ids: z.array(z.number()).optional(),
  records_data: jsonSchema.optional(),
  records_count: z.number().optional(),
  description: z.string().optional().nullable(),
  created_at: z.string().optional(),
  rolled_back_at: z.string().optional().nullable(),
  rolled_back_by_batch_id: z.string().optional().nullable(),
});

export const publicStokRowSchema = z.object({
  alat_name: z.string(),
  amount: z.number(),
  id: z.number(),
});

export const publicStokInsertSchema = z.object({
  alat_name: z.string(),
  amount: z.number(),
  id: z.number().optional(),
});

export const publicStokUpdateSchema = z.object({
  alat_name: z.string().optional(),
  amount: z.number().optional(),
  id: z.number().optional(),
});

export const publicDeleteRecordCompanyNameAndAlatTableDataArgsSchema = z.object(
  {},
);

export const publicDeleteRecordCompanyNameAndAlatTableDataReturnsSchema =
  z.undefined();

export const publicGetUniqueAlatNamesBetweenDatesArgsSchema = z.object({
  start_date: z.string(),
  end_date: z.string(),
});

export const publicGetUniqueAlatNamesBetweenDatesReturnsSchema = z.array(
  z.object({
    name: z.string(),
  }),
);

export const publicRandomFnArgsSchema = z.object({});

export const publicRandomFnReturnsSchema = z.number();

export const publicSaveWorksheetArgsSchema = z.object({
  alat_name: z.string(),
  masuk: z.array(z.number()),
  keluar: z.array(z.number()),
  company_names: z.array(z.string()),
  alat_names: z.array(z.string()),
  tanggal: z.array(z.string()),
});

export const publicSaveWorksheetReturnsSchema = z.undefined();
